### ISSUE TITLE
How can I delete data using graph

### ISSUE THREAD

**Issue by misuqian** [CosmicMind/Graph#101]

**Comment by daniel-jonathan** [comment]
The general form is to use the delete method. For example:

``` swift
let graph: Graph = Graph()
let user: Entity = Entity(type: "User")
//... do somethings
graph.save()

//... do more things

user.delete() // deletes the Entity and the relationships it has. 
graph.save()

```

**Comment by daniel-jonathan** [comment]
If you have any further questions, please reopen or create a new issue. :) All the best!

**Comment by misuqian** [comment]
so fast ! THX!!!

**Comment by adnbsr** [comment]
@danieldahan `graph.delete()` is no longer available.

**Comment by daniel-jonathan** [comment]
@adnbsr `graph.delete` should be now `graph.clear`.

**Comment by adnbsr** [comment]
@danieldahan `graph.clear()` clears all, but I need just for one entity. `entity.delete()` removes entity temporarily. After reopen, data comes again. What should be called after `entity.delete()`?

**Comment by daniel-jonathan** [comment]
@adnbsr You need to save the change after you make one. `entity.delete()` is a change, so call `graph.sync()` or `graph.async()`.
