### ISSUE TITLE
How i get conditional sorted entity array 

### ISSUE THREAD

**Issue by misuqian** [CosmicMind/Graph#103]
sortDescriptors? 
public func sort(@noescape isOrderedBefore: (Self.Generator.Element, Self.Generator.Element) -> Bool) -> [Self.Generator.Element] ? hot to use it ?

**Comment by daniel-jonathan** [comment]
The return result of `graph.search...` is an Array<Type>. This allows you to use the `sort` functionality, such as: 

``` swift
let sorted: Array<Entity> = graph.searchForEntity(types: ["User"]).sort { (a: Entity, b: Entity) -> Bool in
    return (a["age"] as? Int) < (b["age"] as? Int)
}
```

In the above example, you are searching for "User" type Entities and sorting by age. This is really handy, but limited in that you must alway sort the array and compare. If you are looking for a more robust approach, you should look into [Algorithm](https://github.com/CosmicMind/Algorithm), which will allow you to store sorted sets of data.

So you know, if you were to have an Array of Entity objects, when comparing the Entities themselves, they sort based on type and id. 

For example: 

``` swift
let sorted: Array<Entity> = graph.searchForEntity(types: ["User"]).sort { (a: Entity, b: Entity) -> Bool in
    return a < b
}
```

I hope this helps. Please feel free to reopen or create a new issue if you need further assistance.
