### ISSUE TITLE
iCloud 

### ISSUE THREAD

**Issue by alessandrocatoni** [CosmicMind/Graph#105]
Add iCloud support pleaseeee

**Comment by daniel-jonathan** [comment]
Perfect! My aim was to have it for the end of May. I will leave this issue up until then.

**Comment by alessandrocatoni** [comment]
Ok ! Thank's ! You are doing a great job with this library, i am very happy about it and i will mention it in my app
Have a nice day,

**Comment by daniel-jonathan** [comment]
:) Thank you!

**Comment by daniel-jonathan** [comment]
@alessandrocatoni Will be done this soon :) Sorry for any delays.

**Comment by DaniNico** [comment]
Dear all, 
I'm using yours library, 
You have done an excellent job but i need to implement the synchronization with icloud to complete my app. Could you please update your project? 
Thank you and compliments

**Comment by daniel-jonathan** [comment]
Hey, I am working on it today :)

**Comment by daniel-jonathan** [comment]
Hey, an update. I rewrote the internals to support iCloud. What does that mean?

When using iCloud, it is not necessary to save all data to the cloud, and the strategy to save data depends on data type, performance, etc... 

So what did I do? 

I made it that you can now have as many graphs as you like simultaneously that all store data in the strategy you would like. So some data can go to the cloud, and some can stay local, and some can be only memory, etc... 

The API looks like this now:

``` swift
let g = Graph()

let e = Entity("User")

g.save()
```

And using a named Graph:

``` swift
let g = Graph("Cloud")

let e = Entity("User", graph: g)

// or

let e = Entity("User", graph: "Cloud")

g.save()

```

Further more, I fixed a threading issue and context management issue.

So to give you guys an aim of when to expect a release on this, I would say Friday is my latest date. 

Thanks and all the best!

**Comment by alessandrocatoni** [comment]
Ok, thanks!

**Comment by daniel-jonathan** [comment]
So before I release this update, I was wondering if any of you @alessandrocatoni or @DaniNico had any suggestions for the Graph API. Thank you!

**Comment by DaniNico** [comment]
Hi, i can't find a better solution for "API", i think that yours is the best onestly, especially if you Have just tried it and it works correctly. Many thanks

**Comment by daniel-jonathan** [comment]
Thank you :) The release is very close. I am writing new tests.

**Comment by DaniNico** [comment]
Very good, when will you publish it?

**Comment by daniel-jonathan** [comment]
Within the next couple days. I am testing iCloud, making sure it works effectively. I rewrote Graph basically. Sorry for the delays, I ran into some issues I had not anticipated.

**Comment by DaniNico** [comment]
OK, I look forward to, thanks!

**Comment by DaniNico** [comment]
hi, i need to know at what timothy work is. Can you please let me know as soon as possible? 
many thanks

**Comment by DaniNico** [comment]
sorry, at what time

**Comment by daniel-jonathan** [comment]
I am testing the solution. Its a pretty intricate thing, and I don't want to release something that will cause you more errors than benefits. You can follow along the work in the icloud branch. At this point, I am testing iCloud support in an app to see it all work.

**Comment by DaniNico** [comment]
ok, many thanks. i'm waiting

**Comment by daniel-jonathan** [comment]
I think the wait is going to be worth it. In my opinion the whole framework just took a leap forward. Once I can get through the tests, it will be all yours to use :) I'll keep you posted.

**Comment by DaniNico** [comment]
thanks

**Comment by daniel-jonathan** [comment]
@DaniNico will you be free to test the iCloud solution tomorrow? Thank you!

**Comment by DaniNico** [comment]
Of course...I'm ready!! Thank you

**Comment by alessandrocatoni** [comment]
Me too ! Thanks 🙏 

Alessandro Catoni
iOS app Developer 
Cell. +393285798097
Mail: alessandro.catoni@yahoo.it
Web: Facebook.com/sviluppoAlessandroCatoni

**Comment by daniel-jonathan** [comment]
I am going to ask for you to test the development branch in a couple hours. I am making one last update. Then we can do a full release of the new version for 1.2.0. You may want to chat with me while we do this on this [Gitter channel](https://gitter.im/CosmicMind/Graph). Thanks for your patience. I rewrote the entire framework.

**Comment by daniel-jonathan** [comment]
[1.2.0](https://github.com/CosmicMind/Graph/releases/tag/1.2.0) is now available, and you will want to visit the [Gitter Channel](https://gitter.im/CosmicMind/Graph) to learn how to use iCloud. Ping me when ready. Thank you!
