### ISSUE TITLE
Support Core Data Changes In iOS 10

### ISSUE THREAD

**Issue by JARMourato** [CosmicMind/Graph#109]
Just wondering if you've looked into it and how it will affect Graph

**Comment by daniel-jonathan** [comment]
I am about to release iCloud support, running a couple final tests. I think these [changes](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatNewCoreData2016/ReleaseNotes.html) will be wonderful for Graph and I will most likely start updating Graph at the end of the month, with the [Material](https://github.com/CosmicMind/Material) iOS 10 updates. I also rewrote Graph completely, so I think overall the framework is going to get much better.

**Comment by daniel-jonathan** [comment]
If you would like to be up to date and chat, there is a [Gitter channel](https://gitter.im/CosmicMind/Graph) that I will be available on :)
