### ISSUE TITLE
Add JSON parser / Network and exporter for Graph.

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Graph#110]
This should allow graph to send and receive data through a network and JSON objects.

**Comment by ghost** [comment]
This would be very welcome :). I had something working a few weeks ago based on your advice in Issue 95  -- but it was a lot of boilerplate. Being able to download and map JSON objects to Entities in the Graph would make aggregating data from multiple API's much easier. Many thanks for looking at this. I'll be a willing tester

**Comment by daniel-jonathan** [comment]
@DavidELeahy perfect :) Glad this will help.

**Comment by eonist** [comment]
Would love to see this.

**Comment by multinerd** [comment]
any updates on this?

**Comment by daniel-jonathan** [comment]
@multinerd I have made some progress on this. I am updating Graph and it's API with an inclusion for this during this month. Sorry for any inconvenience :)

**Comment by EmilGram2** [comment]
Update?

**Comment by daniel-jonathan** [comment]
The JSON parser is available. The networking is not. Soon enough this will be done fully.

**Comment by daniel-jonathan** [comment]
Let's follow this issue as the feature is being added. https://github.com/CosmicMind/Graph/issues/148
