### ISSUE TITLE
Wikipedia links

### ISSUE THREAD

**Issue by eonist** [CosmicMind/Graph#112]
Would love to see some wikipedia links to these subjects:

Relationship Modeling
 Action Modeling For Analytics
 Model With Graph Theory and Set Theory
 Faceted Search API

Or other good links/books

**Comment by daniel-jonathan** [comment]
I agree :) I am currently reworking Graph's API. I am putting a lot of effort in teaching how to use Graph in many scenarios. So please stay tuned and thank you for your support.

**Comment by eonist** [comment]
**Relationship Modeling**
https://en.m.wikipedia.org/wiki/Entity–relationship_model

**Action Modeling For Analytics**
https://en.m.wikipedia.org/wiki/Action_model_learning

**Model With Graph Theory** 
https://en.m.wikipedia.org/wiki/Graph_theory

**Set Theory**
https://en.m.wikipedia.org/wiki/Set_theory

**Faceted Search**
https://en.m.wikipedia.org/wiki/Faceted_search

**Comment by daniel-jonathan** [comment]
Awesome! Great resources. There is a new tagging system being added as well :) All will be released in Graph 2

**Comment by eonist** [comment]
Maby a couple of awesome examples is enough to lure people into using Graph. As opposed to many examples. Easier to maintain as well. Ive previously made an sqlite api: https://github.com/eonist/SqliteEdit  Were I try to explain its use through a table. Databases are tables and github markdown aupports table syntax. Just an idea.

**Comment by daniel-jonathan** [comment]
Yeah, I plan to have examples that really show how to do cool things and highlight why using Graph is a great choice. I haven't had a chance to do that, so I will be doing it with the latest revisions.

**Comment by eonist** [comment]
Would be awesome to see Graph in conjunction with Your IOS UI framework. Like some spiffy gifs showing off  semi inteligent list searches etc.

**Comment by eonist** [comment]
Also what do you think about the analysis of this post : http://stackoverflow.com/a/16149607/5389500

**Comment by daniel-jonathan** [comment]
My general thinking is that CoreData is the best approach on anything Apple. It really allows a consistent approach to solving problems. My background in databases is over 16 years and I was managing 1 billion hits a day. So I understand databases, and I think the arguments made today against CoreData come from arguments that exist in different development/environment issues.

**Comment by eonist** [comment]
Well here is to CoreData then 🎉 Hopefully your Graph project can shed some spotlight on CoreData. Other good sources for CoreData are the WWDC videos that apple makes. You should maybe make a section on CoreData in the wiki section of this project?

**Comment by daniel-jonathan** [comment]
I think you said the best approach, which is to make examples that show how awesome CoreData and Graph are. This is what I will be doing through tutorials, and through an app I am launching for iOS 10.

**Comment by eonist** [comment]
Sounds good. Have you checked this book: "Chris Eidhof - Core Data" https://www.objc.io/books/core-data/ ?

**Comment by daniel-jonathan** [comment]
No I haven't. Looks like a good read though :) I am going to make note of the links you shared. For now I am going to close this issue, as it doesn't describe anything to solve. Let's continue this chat on [Gitter](https://gitter.im/CosmicMind/Graph). All the best!
