### ISSUE TITLE
duplicate entity after update

### ISSUE THREAD

**Issue by VitoPietrapertosa** [CosmicMind/Graph#114]
Hi,
when I try to update an antity after searching, this particular entity is duplicated.
This is my code:
`let existElement = graph.searchForEntity(properties: [(key: "username", value: username), ("id", id)]`
`if existElement.count == 1 {

existElement[0]["id"]  = id
existElement[0]["username"] = username
}
graph.async() {  (success: Bool, error: NSError?)  in  
 if let error e = error {    do something }
}
`

**Comment by daniel-jonathan** [comment]
Hey! I will look into this over the weekend. I have been away, so sorry for any delay. I think it might be a search result issue. Also, please provide the version of Graph you are using. Thank you!

**Comment by VitoPietrapertosa** [comment]
hi, thank you for replay.
My Version is last version available on gitHub. I'm waiting for your news.

**Comment by daniel-jonathan** [comment]
Hey, I have allowed this to slip away. I haven't been able to reproduce the issue, and we are working on Graph 2 which is currently in the development branch. If this issue still persists for you, please reopen or create a new issue. Sorry for the late response on this.
