### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by andreadelfante** [CosmicMind/Graph#115]
Is there a closure or something to perform a migration from an old version to a new one?

**Comment by daniel-jonathan** [comment]
I will work on that before I release Graph 2 in October :)

**Comment by daniel-jonathan** [comment]
Hey, This is really old and I never had a chance to make the migration tool. If there is another major change that requires this, I will add it. For now, I am going to close this issue. Sorry for any inconvenience and thank you :)
