### ISSUE TITLE
iOS 10 issue, where iCloud needs to be outlined on its usage. 

### ISSUE THREAD

**Issue by DaniNico** [CosmicMind/Graph#121]
Hi, I need the documentation to initialize Graph with iCloud for iOS 10

**Comment by daniel-jonathan** [comment]
I am working more on this tonight. So should be in yours hands very soon :)

**Comment by DaniNico** [comment]
Ok, thanks! :)

**Comment by daniel-jonathan** [comment]
Making an update and then sharing an example project with Graph setup. I realized I could make things a bit more organized. This should be ready tonight. Thanks for you patience.

**Comment by DaniNico** [comment]
Ok, thank you very much .. I wait

**Comment by daniel-jonathan** [comment]
I found an issue with iOS 10 and iCloud. I found that it is not persisting. It may be a configuration issue on my part, so I am investigating this. I have already made some updates that make it easier to interact with Graph. This is the highest priority for me now, so I will keep you posted. Thank you!

**Comment by DaniNico** [comment]
Ok, I hope for your own solution in the shortest time. look forward

**Comment by daniel-jonathan** [comment]
Thank you!

**Comment by daniel-jonathan** [comment]
I tested iOS 10 with iCloud and Graph, works perfectly. I will write your note today :) Thank you!

**Comment by DaniNico** [comment]
Ok, thank!   :)

**Comment by daniel-jonathan** [comment]
Documentation is now available for [Grpah with iCloud](http://cosmicmind.com/graph/icloud).
