### ISSUE TITLE
Result enum looks like is unused and is in conflict against Alamofire

### ISSUE THREAD

**Issue by swiftsrl** [CosmicMind/Graph#123]
at line 134 of File.swift there's an enum that looks like is unused and is in conflict against Alamofire

```
public enum Result {
    case success
    case failure(error: Error)
}
```
can we delete it, or is used somewhere?

**Comment by daniel-jonathan** [comment]
Hey, nice catch. Please find a fix in [Graph 2.1.2](https://github.com/CosmicMind/Graph/releases/tag/2.1.2). All the best!
