### ISSUE TITLE
iCloud feature doesn't works for new projects

### ISSUE THREAD

**Issue by swiftsrl** [CosmicMind/Graph#127]
Just make a new project, turn on iCloud, make an instance of Graph using the cloud init (where is not clear the purpose of the string you have to pass), make a new record and save the db, and finally setup a search, run it and you'll see the returned array is always empty

**Comment by daniel-jonathan** [comment]
I think this might be an issue because of the version of iOS that is being used. Are you using 10.2 when you build a new project?

**Comment by swiftsrl** [comment]
yes 10.2

**Comment by daniel-jonathan** [comment]
Okay, I will make a new project and see what the issue is, and if there is one, I will fix it right away :) Thanks for sharing this.

**Comment by swiftsrl** [comment]
hello Daniel
news about that?

**Comment by daniel-jonathan** [comment]
Yes, sorry. I was caught up in some other issues. I will take a look at this today, and aim to have an update by the end of the week, if not earlier. Thank you!

**Comment by daniel-jonathan** [comment]
Hey, so I have tested this out again and all seems to work. I am not sure what if going on with your project. Can you verify in any way that iCloud is working for you?

I am currently able to sync data between my iPhone 6s and iPad Pro using 10.2.1.

**Comment by swiftsrl** [comment]
here are the steps:
- New Xcode project
- Turn on iCloud, all is ok (no red dots, no errors, the Entitlement is good)
- Make an instance of Graph:
`db = Graph(cloud: "FantasyName")`
- Put in some data:
```
let record = Entity(type: "Names")
record["name"] = name
```
- save the db:
`db.sync()`
- arrange and perform the search:
```
let search = Search<Entity>(graph: self.db).for(types: ["Names"])
self.storage = search.sync(completion: nil)
```
- the storage Array is always empty....
so what's wrong with this????

**Comment by daniel-jonathan** [comment]
Are you doing these steps after the `graphDidPrepareCloudStorage` call?

**Comment by swiftsrl** [comment]
yes, just tried this:
```
func graphDidPrepareCloudStorage(graph: Graph) {
        debugPrint("graphDidPrepareCloudStorage")
        
        self.addName("Apple")
        self.addName("Google")

    }
```
the func:
```
func addName(_ name:String) {
        
        let record = Entity(type: "Names")
        record["name"] = name        
        db.sync()
        
        let search = Search<Entity>(graph: self.db).for(types: ["Names"])
        self.storage = search.sync(completion: nil)
        self.lc?.tableView.reloadData()
        
    }
```
but the search result is always empty....

**Comment by daniel-jonathan** [comment]
Okay, the best bet is to send me a sample with it not working, or what you have, and then I can test it. I need to see what is happening here. Thank you!

**Comment by swiftsrl** [comment]
ok, this is the test
[GraphCloudTest.zip](https://github.com/CosmicMind/Graph/files/890708/GraphCloudTest.zip)

**Comment by daniel-jonathan** [comment]
Thank you, I will look at this in a few hours :)

**Comment by swiftsrl** [comment]
Thanks to one of my students I found the bug:
- if you make a record this way everything works fine:
`let record = Entity(type: "Names", graph: self.db)`
- but if you use this init it doesn't:
`let record = Entity(type: "Names")`
see you next trouble :)

**Comment by daniel-jonathan** [comment]
Yes, that is correct. Because the Entity doesn't know which Graph you are referencing and without it specified, it goes to the default local Graph. Sorry, I didn't catch this earlier.
