### ISSUE TITLE
Relationship Deletion

### ISSUE THREAD

**Issue by lazarte** [CosmicMind/Graph#128]
How can we delete the relationship and their all relationships(subject and object). Seems like when trying to `relationship.delete()` will not delete its Entities(subject and object).

**Comment by daniel-jonathan** [comment]
Deletion works like this:

When deleting an Entity, all Relationships and Actions are deleted but not the Entities that connected them. When you delete a Relationship or Action, none of the Entities are deleted. The reason for this, is that, Entities are considered the data points that build all the relationships between them, whether that be a direct relationship or action. So if you had books in a system, and they were of type Book, you would not necessarily want to delete that Book when deleting a relationship between the Book and another Entity, such as a User. But if you deleted the User, then the relationship could not exist, so it is deleted. To do a full delete of Relationships and their Entities, you would need to do something like this. 

```swift
relationship.subject?.delete()

relationship.object?.delete()

relationship.delete()

graph.sync() // or graph.async()
```

The entire deletion is done in a transaction, so nothing will be deleted unless everything is deleted. 

Please reopen the issue if you need :) Thank you!

**Comment by lazarte** [comment]
Hi @danieldahan still its not clear to me how I can proper way to delete the subjects and objects. Please see below code sample code

```
let graph = Graph()
// Create a Person Entity.
let mark: Entity = Entity(type: "Person")
mark["firstName"] = "Mark"
mark["lastName"] = "Zuckerberg"

// Create a Company Entity.
let facebook: Entity = Entity(type: "Company")
facebook["name"] = "Facebook"

// Create an Employee Relationship.
let employee: Relationship = Relationship(type: "Employee")
employee["startDate"] = "February 4, 2004"

// Form the relationship.
employee.subject = facebook
employee.object = mark


// Create a Task Entity.
let task: Entity = Entity(type: "Task")
task["description"] = "ToDo"

// Create an Tasks Relationship.
let tasks: Relationship = Relationship(type: "Tasks")
tasks.subject = mark
tasks.object = task

graph.sync()
```

What is the best way to delete the Employee and Task Relationship including their subject and object.

```
let search = Search<Relationship>(graph: graph).for(types: "Employee")
let relationships = search.sync()

for relationship in relationships {
    // HOW TO DELETE
}
```

**Comment by daniel-jonathan** [comment]
Sorry, I edit my answer. I thought of the Relationship as an Action relationship type. 

This is the updated code with your code:

```swift
let search = Search<Relationship>(graph: graph).for(types: "Employee")
let relationships = search.sync()

for relationship in relationships {
    relationship.subject?.delete()
    relationship.object?.delete()
    relationship.delete()
}
graph.async()
```

Let me know :)

**Comment by lazarte** [comment]
What about the Task Relationship?

**Comment by daniel-jonathan** [comment]
Because `Mark` is part of the `Employee` relationship, when you delete  him as an `object`, his relationships will be deleted, which will delete the `Tasks` relationship, but not the `Facebook` instance of type `Company`.

**Comment by lazarte** [comment]
So I'm doing this one..

```
let search = Search<Relationship>(graph: graph).for(types: "Employee")
let relationships = search.sync()
        
if relationships.count > 0 {
    let relationship = relationships[0]
    relationship.object?.delete()
    
    relationship.delete()
}
```

I want to delete `Employee` relationship and Employee's object `Mark` as well as `Mark` task will give me an error `The operation couldn\U2019t be completed. (Cocoa error 1570.)`.

**Comment by daniel-jonathan** [comment]
Well this will never change `let relationship = relationships[0]`. Why are you writing that line? You would need to remove the `relationship` from the `relationships` Array for this to work as a dequeue from your Array.

**Comment by lazarte** [comment]
Actually it was a table list, I need to remove one item when doing a delete. It was a list of relationships of type `Employee` with subject `Company` and object `Person`. The `Person` is also a subject of the relationship `Tasks` with an object of `Task`.  The sample code above shows the relationships. When doing a delete on one row should remove the `Employee` relationship, Employee relationship object `Person` and the `Tasks` relationship subject and object.

`let relationship = relationships[row]`

**Comment by daniel-jonathan** [comment]
Ahh... cool :)
