### ISSUE TITLE
Links Down

### ISSUE THREAD

**Issue by troy21688** [CosmicMind/Graph#130]
I am trying to click the sample projects related to the Live SearchBar and it appears the link is down. Any way for me to access? Thanks again.

**Comment by daniel-jonathan** [comment]
Thank you for submitting this issue. I have corrected it in [Graph 2.1.4](https://github.com/CosmicMind/Graph/releases/tag/2.1.4). The link you are looking for is: [Sample Search Project](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/Search). All the best!
