### ISSUE TITLE
Multiple parameters used in search fail when using the `.and` search type. 

### ISSUE THREAD

**Issue by marrocmau** [CosmicMind/Graph#132]
Where can I find some documentation with examples of filters or counters or others?

**Comment by daniel-jonathan** [comment]
I don't have many at the moment. If you share a scenario with me, I can show you how to approach it.

**Comment by marrocmau** [comment]
Hi,
i have this relationship case :
 [TRIP] 1-N [USERS]

	    let users1 = Entity(type: Const.USERS)
            users1["name"]="John"
            users1["date"]="08/05/2017"
            users1["image"]="img1"
            
            let users2 = Entity(type: Const.USERS)
            users2["name"]="Jack"
            users2["date"]="08/05/2017"
            users2["image"]="img2"
            
            let record1 = Entity(type: Const.TRIP)
            record1["trip"]="USA"
            record2["vehicle"]="CAR"
            users1.is(relationship: Const.SUBSCRIBERS).in(object: record1)
            users2.is(relationship: Const.SUBSCRIBERS).in(object: record1)
            
            let record2 = Entity(type: Const.TRIP)
            record1["trip"]="CANADA"
            record2["vehicle"]="BOAT"
            users2.is(relationship: Const.SUBSCRIBERS).in(object: record2)

Is it correct?
How do I search to find only users who are related to the USA? (and - example- use the result for print all users attributes in output)

**Comment by daniel-jonathan** [comment]
Hey, 

Here is a sample based on your original code:

```swift
let graph = Graph()
graph.clear()
        
let search = Search<Relationship>(graph: graph).for(types: "Subscriber")
        
let users1 = Entity(type: "User")
users1["name"]="John"
users1["date"]="08/05/2017"
users1["image"]="img1"
        
let users2 = Entity(type: "User")
users2["name"]="Jack"
users2["date"]="08/05/2017"
users2["image"]="img2"
        
let trip1 = Entity(type: "Trip")
trip1["location"]="USA"
trip1["vehicle"]="CAR"
        
users1.is(relationship: "Subscriber").of(object: trip1)
users2.is(relationship: "Subscriber").of(object: trip1)
        
let trip2 = Entity(type: "Trip")
trip2["location"]="CANADA"
trip2["vehicle"]="BOAT"
        
users2.is(relationship: "Subscriber").of(object: trip2)
        
graph.sync()
        
let result = search.sync().filter { (subscriber) -> Bool in
    return "USA" == subscriber.object?["location"] as? String
}
        
let users = result.subject(types: "User")
        
print(users)
```

Hope this helps and feel free to ask more questions :) Reopen the issue if you need. All the best!

**Comment by marrocmau** [comment]
Hi, Is it possible to create N-relationship?
I mean:
Users -> (subscriber="Trip") -> TRIP -> (subscriber="Expense") -> "Exepense"?

This is a example:
```
let expense1 = Entity (Type: "Expense")
expense1["descr"] = "one"
expense1["amount"] = "50"

let expense2 = Entity (Type: "Expense")
expense2["descr"] = "two"
expense2["amount"] = "150"

expense1.is(relationship: "Subscriber").of(object: trip2)
expense2.is(relationship: "Subscriber").of(object: trip2)
```

When try to find "exepense" i find nothind.
Can you help me?
thanks

**Comment by daniel-jonathan** [comment]
Sure I can help. I need to understand more. Why does your `Expense` type subscribe to the `Trip` type? In general, yes, Graph is meant to manage many complex relationships. Also, let's move this conversation to [Graph Gitter](https://gitter.im/CosmicMind/Graph) please. Thank you!

**Comment by marrocmau** [comment]
Hi, 
because i want create something like 
<img width="495" alt="screen shot 2017-05-30 at 10 18 06" src="https://cloud.githubusercontent.com/assets/914987/26574354/54b0ce0a-4521-11e7-8823-e2373facc69c.png">

Can I use "group" function to organize all Expense Receipts?
Ex:
```
let expense1 = Entity (Type: "Expense")
expense1["descr"] = "one"
expense1["amount"] = "50"
expense1.add(to: trip1["location"])
expense1.add(to: users2["name"])
```

**Comment by daniel-jonathan** [comment]
You would be better off making an Entity for each Expense and then attach it as a receipt of, not a Subscriber. 

`Expense -> Receipt -> (of) Trip <- Subscriber <- User`

I wouldn't use groups in this case.

**Comment by marrocmau** [comment]
What means "attach it as receipt of" ?

**Comment by daniel-jonathan** [comment]
Make the relationship between the two. Sorry, I was using different wording, but that is what I meant.

**Comment by marrocmau** [comment]
Sorry Daniel,
but i have only 3 tables: Users, Trip and Expense (expense represent our Expense Receipt).
I review the code and now i have created another "relationship": ExpenseReceipt
```
let graph = Graph()
graph.clear()  
 
let users1 = Entity(type: "User")
users1["name"]="John"
users1["date"]="08/05/2017"
users1["image"]="img1"
        
let users2 = Entity(type: "User")
users2["name"]="Jack"
users2["date"]="08/05/2017"
users2["image"]="img2"
        
let trip1 = Entity(type: "Trip")
trip1["location"]="USA"
trip1["vehicle"]="CAR"
        
users1.is(relationship: "Subscriber").of(object: trip1)
users2.is(relationship: "Subscriber").of(object: trip1)
        
let trip2 = Entity(type: "Trip")
trip2["location"]="CANADA"
trip2["vehicle"]="BOAT"
        
users2.is(relationship: "Subscriber").of(object: trip2)

let expense1 = Entity (Type: "Expense")
expense1["descr"] = "Lunch"
expense1["amount"] = "50"
expense1["trip"]= "CANADA"
expense1["user"]="John"

let expense2 = Entity (Type: "Expense")
expense2["descr"] = "Hotel"
expense2["amount"] = "150"
expense2["trip"]= "CANADA"
expense2["user"]="Jack"

expense1.is(relationship: "ExpenseReceipt").of(object: trip2)
expense2.is(relationship: "ExpenseReceipt").of(object: trip2) 
let search = Search<Relationship>(graph: graph).for(types: "ExpenseReceipt")
 let result = search.sync().filter { (subscriber) -> Bool in
            return ("CANADA" == subscriber.object?["trip"] as? String &&
                    "Jack" == subscriber.object?["user"] as? String
                    )
        }
```
The result is empty...

Did I do something wrong?

**Comment by danieldahan** [comment]
I haven't tried your code but you have an impossible condition to be satisfied. 

```swift
return ("CANADA" == subscriber.object?["trip"] as? String && "Jack" == subscriber.object?["user"] as? String
```

The object cannot be a user and trip simultaneously.

**Comment by daniel-jonathan** [comment]
I haven't tried your code but try changing your object in your condition to subject. It looks like the Expense is the subject, not object.

**Comment by marrocmau** [comment]
Hi Daniel,
I modified my code .... I have abandoned the relationships and I tried to use Search<entity> whit properties:
```
       let graph = Graph()
        graph.reset()
        graph.clear()
        
        let users1 = Entity(type: "User")
        users1["name"]="John"
        users1["date"]="08/05/2017"
        users1["image"]="img1"
        
        let users2 = Entity(type: "User")
        users2["name"]="Jack"
        users2["date"]="08/05/2017"
        users2["image"]="img2"
        
        let trip1 = Entity(type: "Trip")
        trip1["location"]="USA"
        trip1["vehicle"]="CAR"
        
        users1.is(relationship: "Subscriber").of(object: trip1)
        users2.is(relationship: "Subscriber").of(object: trip1)
        
        let trip2 = Entity(type: "Trip")
        trip2["location"]="CANADA"
        trip2["vehicle"]="BOAT"
        
        users2.is(relationship: "Subscriber").of(object: trip2)
        
        let expense1 = Entity (type: "Expense")
        expense1["descr"] = "Lunch"
        expense1["amount"] = "50"
        expense1["trip"] = "CANADA"
        expense1["user"] = "John"
        
        let expense2 = Entity (type: "Expense")
        expense2["descr"] = "Hotel"
        expense2["amount"] = "150"
        expense2["trip"] = "CANADA"
        expense2["user"] = "Jack"
           
        let search2 = Search<Entity>(graph:graph).for(types: "Expense").where(properties: [("user","Jack"),("trip","CANADA")],using: SearchCondition.and)
        
        for record in search2.sync() {
              print("\n",record,"\n")
        }
```
I would have expected only one record and instead I have this result:
<img width="984" alt="screen shot 2017-06-01 at 11 28 23" src="https://cloud.githubusercontent.com/assets/914987/26673734/37da2efe-46be-11e7-97b6-5333426003ce.png">

the **SearchCondition.and** not works like SQL "WHERE ...AND..." condition?

**Comment by daniel-jonathan** [comment]
This is really interesting. I tried it and you are right, there seems to be a bug here. I will file this as a bug and fix it up.

**Comment by daniel-jonathan** [comment]
The new `development` branch will have a fix for this. Thank you!
