### ISSUE TITLE
Graph 2.1.4 not work with xCode 9.0 -> swift 4 

### ISSUE THREAD

**Issue by sterzo** [CosmicMind/Graph#138]
/Pods/Graph/Sources/Graph.swift:129:54: Static let 'name' is internal and cannot be referenced from a default argument value

/Pods/Graph/Sources/Graph.swift:129:97: Static let 'type' is internal and cannot be referenced from a default argument value

/Pods/Graph/Sources/File.swift:217:134: Cannot convert value of type '[String : Any]?' to expected argument type '[FileAttributeKey : Any]?'

**Comment by daniel-jonathan** [comment]
Please use the [development](https://github.com/CosmicMind/Graph/tree/development) branch :)

**Comment by sushmakc** [comment]
Hi,

I still get this issue /Pods/Graph/Sources/File.swift:217:134: Cannot convert value of type '[String : Any]?' to expected argument type '[FileAttributeKey : Any]?'
