### ISSUE TITLE
Issues with iCloud to get data from iCloud with Graph

### ISSUE THREAD

**Issue by NicoloCurioni** [CosmicMind/Graph#139]
Hi, I have an issues that I don't know why with my **DataManager.swift** and Graph implementation I can't get **iCloud data**. I don't know why, if an issue of containers of other kind of problem.
[DataManager.zip](https://github.com/CosmicMind/Graph/files/1334488/DataManager.zip)

All Graph implementation is available inside DataManager.swift file.

Thanks... I will wait to get new updates.

**Comment by daniel-jonathan** [comment]
@Nicolo1236DevItalia do you need help with this still? Or is it meant to be closed?

**Comment by NicoloCurioni** [comment]
Thanks, but I have resolved this issue. Thanks but I closed this issues.

Dear Regards, NicoDevItalia

**Comment by daniel-jonathan** [comment]
Great! Feel free to leave any helpful details for anyone else. Thank you!
