### ISSUE TITLE
Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'

### ISSUE THREAD

**Issue by donghd** [CosmicMind/Graph#140]
I tried to build Search samples, but I got compile error:
> File.swift (217): Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'

**Comment by daniel-jonathan** [comment]
Are you using Swift 4? Graph is available in Swift 4 from the latest release.

**Comment by daniel-jonathan** [comment]
If this continues to be an issue, please reopen this issue. Thank you!
