### ISSUE TITLE
Exporting Graph

### ISSUE THREAD

**Issue by Shempaiii** [CosmicMind/Graph#141]
Can we export Graph? like for example in CoreData we can get the .sqlite file.

**Comment by daniel-jonathan** [comment]
Graph creates .sqlite files, so you can export it that way. There isn't a feature yet to export it into another format. That said, we should create an export function that dumps everything to JSON.

**Comment by Shempaiii** [comment]
Ah I see, Thanks for the reply. :)

**Comment by daniel-jonathan** [comment]
Thank you! I am going to close this for now.
