### ISSUE TITLE
GraphJSON write support

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Graph#148]
`GraphJSON` is read-only as of now. It should support writing as well.

```swift
let json = GraphJSON(...)
json.user.name = "Orkhan" 
json.user.age= 20
```

**Comment by daniel-jonathan** [comment]
Linking this feature request https://github.com/CosmicMind/Graph/issues/110. Let's follow this issue. Closing #110.

**Comment by daniel-jonathan** [comment]
Solved in https://github.com/CosmicMind/Graph/pull/150#pullrequestreview-145496063.
