### ISSUE TITLE
SearchCondition support for member(of:) and has(tags:)

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [CosmicMind/Graph#149]
`member(of groups: [String])` and `has(tags: [String])` should be able to be queried with `or` and `and` search condition. Just like in Search<T>
```swift
person.member(of: ["family", "parent"], using: .and)
person.has(tags: ["family", "parent"], using: .or)
```

**Comment by daniel-jonathan** [comment]
Solved in https://github.com/CosmicMind/Graph/pull/151#pullrequestreview-145835988
