### ISSUE TITLE
Graph cocoapod doesn't compile on mojave. 

### ISSUE THREAD

**Issue by adamdahan** [CosmicMind/Graph#157]
haseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/adamdahan/Library/Developer/Xcode/DerivedData/SlidesMagic-emvmfauqtzdwbmbkoocajpdmpqel/Build/Intermediates.noindex/SlidesMagic.build/Debug/SlidesMagic.build/Script-55AADEECA68DE02ED3F5F3A6.sh (in target: SlidesMagic)
    cd /Users/adamdahan/Desktop/SlidesMagic8V3-Final
    /bin/sh -c /Users/adamdahan/Library/Developer/Xcode/DerivedData/SlidesMagic-emvmfauqtzdwbmbkoocajpdmpqel/Build/Intermediates.noindex/SlidesMagic.build/Debug/SlidesMagic.build/Script-55AADEECA68DE02ED3F5F3A6.sh

mkdir -p /Users/adamdahan/Library/Developer/Xcode/DerivedData/SlidesMagic-emvmfauqtzdwbmbkoocajpdmpqel/Build/Products/Debug/SlidesMagic.app/Contents/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/adamdahan/Library/Developer/Xcode/DerivedData/SlidesMagic-emvmfauqtzdwbmbkoocajpdmpqel/Build/Products/Debug/Graph/Graph.framework" "/Users/adamdahan/Library/Developer/Xcode/DerivedData/SlidesMagic-emvmfauqtzdwbmbkoocajpdmpqel/Build/Products/Debug/SlidesMagic.app/Contents/Frameworks"
building file list ... done
Graph.framework/
Graph.framework/Graph -> Versions/Current/Graph
Graph.framework/Resources -> Versions/Current/Resources
Graph.framework/Versions/
Graph.framework/Versions/Current -> A
Graph.framework/Versions/A/
Graph.framework/Versions/A/Graph
Graph.framework/Versions/A/Resources/
Graph.framework/Versions/A/Resources/Info.plist

sent 1197186 bytes  received 106 bytes  2394584.00 bytes/sec
total size is 1196634  speedup is 1.00
/Users/adamdahan/Desktop/SlidesMagic8V3-Final/Pods/Target Support Files/Pods-SlidesMagic/Pods-SlidesMagic-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by daniel-jonathan** [comment]
The `development` branch works and will be release soon. It is stable for use. Thank you!
