### ISSUE TITLE
RDF modeling support?

### ISSUE THREAD

**Issue by maximveksler** [CosmicMind/Graph#158]
Hi,

This seems truly great.

Have you considered (and if you have I would love to hear you thoughts on this) buying into the semantic web eco system? (https://github.com/semantalytics/awesome-semantic-web)

**Comment by daniel-jonathan** [comment]
Hey! We are open to all ideas. I looked at the README, but didn't see anything that clearly showcases what we should consider. May you describe a bit more what your idea would be?
