### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by pjebs** [CosmicMind/Graph#161]
Is this project still actively being developed or is it stable?

**Comment by daniel-jonathan** [comment]
Hey @pjebs, it is very stable and very much alive. We are preparing notes for big updates. All the best!

**Comment by OrkhanAlikhanov** [comment]
@pjebs, check out [`development`](https://github.com/CosmicMind/Graph/tree/development) branch it has tons of updates.
```ruby
pod 'Graph', :branch => 'development'
```
