### ISSUE TITLE
Maybe a bug, But more likely something im doing wrong 

### ISSUE THREAD

**Issue by NinjaIshere** [CosmicMind/Graph#79]
```
private func internalSelect(x: RedBlackNode<Key, Value>, order: Int) -> RedBlackNode<Key, Value> {
    validateOrder(order)
    var r: Int = x.left.order + 1
    if order == r {
        return x
    } else if order < r {
        return internalSelect(x.left, order: order)
    }
    return internalSelect(x.right, order: order - r)
}
```

I keep getting " fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) "

Seems to happen after hitting this line of code in my project 
var randomWordFromWords = graph.search(Entity: "Word")[randomNumber()]

<img width="1415" alt="screen shot 2015-09-03 at 10 59 02 am" src="https://cloud.githubusercontent.com/assets/8978522/9666429/d26d11d2-522a-11e5-9217-9a66230a95ae.png">

**Comment by daniel-jonathan** [comment]
can you post the randomNumber() code? and the code that surrounds that logic.

**Comment by NinjaIshere** [comment]
Here is the randonNumber() code and the rest of the code around it 

//
//  WordGenerator.swift
//  RapWordGenerator
//
//  Created by Mind Ooze on 8/25/15.
//  Copyright (c) 2015 NinjaSkillz. All rights reserved.
//

import UIKit
import GraphKit

class WordGenerator: NSObject

{
    let graph: Graph = Graph()

```
func extractWordsFromList() -> NSArray
{
    var arrayOfWords = [NSString]();

    //Reads csvWordList.csv and puts all words into an array
    if let wordFilePath = NSBundle.mainBundle().pathForResource("csvWordList", ofType: "csv") {
        if let wordFile = NSString(contentsOfFile: wordFilePath, usedEncoding: nil, error: nil) {
            arrayOfWords = wordFile.componentsSeparatedByString("\n") as! [NSString]
        }
    }   else { arrayOfWords = ["ERROR!!!!!!"] }

    return arrayOfWords;
}

func createEntityForEachWordInList()
{
    var arrayOfWords = extractWordsFromList()

    for aWord in arrayOfWords {

        var word: Entity? = graph.search(Entity: "Word").last
        if nil == word {
            word = Entity(type: "Word")
            word!["text"] = aWord
            graph.save()
        }
    }

}

func amountOfWordsInList() -> Int
{
    //Gets count of all the words in the array
    var wordsInArray = extractWordsFromList()
    var amountOfWordsInArray = wordsInArray.count

    return amountOfWordsInArray
}

func randomNumber() -> Int
{
    // Returns a random number
    let min = 0
    let max = amountOfWordsInList()
    return Int(arc4random_uniform(UInt32(max - min)))
}

func returnWordFromGraphKit() -> NSString
{
    createEntityForEachWordInList()
    var randomWordFromWords = graph.search(Entity: "Word")[randomNumber()]
    var wordFromGK:NSString;

    wordFromGK = randomWordFromWords["text"] as! NSString

    return wordFromGK
}
```

}

**Comment by daniel-jonathan** [comment]
So it looks like there is a logic issue. 

``` swift
createEntityForEachWordInList
```

call, you are always checking for the last word, and if one exists, you don't actually save any new ones. 

Once you populate a single Word Entity, the graph.search(Entity: "Word").last call will return a value. This will stop you from ever inserting more than one word. 

What you should do, is check if a Word Entity with the property value exists. 

``` swift
func .... () {

var word: Entity? = graph.search(EntityProperty: "text", value: "word to check").last
if nil == word {
    word = Entity(type: "Word")
    word!["text"] = "word to check"
    graph.save()
}
```

Your max number is based on the word count in the file size, but you are passing it to Graph, which will have a different size as you are not passing in the correct range. Your range should be

var words = graph.search(Entity: "Word")

min = 0 to max = words.count, 

where count is the total number of words, so the index check, [randomNumber()] should be from 0 - (count - 1).

**Comment by NinjaIshere** [comment]
Awesome thanks, i will make the changes and let you know.

**Comment by daniel-jonathan** [comment]
Cool, I will close the issue, and you may reopen it if the problem persist. :)
