### ISSUE TITLE
Graph store url

### ISSUE THREAD

**Issue by JARMourato** [CosmicMind/Graph#98]
Hi, is there any plans for providing a way to pass the graph location when creating ? Imagine that I want to share data between an iOS app and a Today Extension, I would have to use a shared container, which means Graph would have to be located there. 

How could i do that using Graph ?

**Comment by daniel-jonathan** [comment]
Hey, That isn't something that is available through an API at the moment, but I do like the idea of that flexibility. So let's leave this issue up and I will put it in the next release. If you wanted to do it yourself for now, until the release -- look in the Graph.swift file, and there is a computed property called persistentStoreCoordinator, you can change the location of the store there.

**Comment by JARMourato** [comment]
Thanks for the answer. Will do that :)

**Comment by misuqian** [comment]
maybe
NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).last! as String

**Comment by daniel-jonathan** [comment]
@misuqian This isn't an issue of getting the location, more so, I believe @JARMourato wants to control the location. This is coming up soon as we make additions to Graph.

**Comment by JARMourato** [comment]
Yes @danieldahan, you are correct. It's is not an issue, it's an enhancement I suggested @misuqian. 

Really looking forward to those additions ;)

**Comment by daniel-jonathan** [comment]
I will start working on it tomorrow and give you an update or a release based on the outcome :) @JARMourato.

**Comment by daniel-jonathan** [comment]
Hi @JARMourato, 

I made an update to Graph, version 1.0.8, where you can now specify the storage location, name, and type. For example:

``` swift
Graph.storeName = "NewStorageName.sqlite"
Graph.storeURL = File.URL(.DocumentDirectory, path: "Graph/NewStorageLocation")
// Graph.storeType = NSSQLiteStoreType
```

These values need to be set prior to using Graph. Once Graph is initialized, these values will have no affect. 

I hope this solves your issue. If not, please reopen the issue, or create a new one :) 

All the best!

**Comment by JARMourato** [comment]
Many thanks @danieldahan  :D

**Comment by xemacobra** [comment]
I was just about to ask for the same thing and then thought I'd read the previous posted issues first. Thanks. This will be helpful for me as well.
